/**
 * A stand-in for the live ledger corpus.
 *
 * Copied verbatim from round one's winning approach (ledger-dashboard/a4) so
 * the two rounds are argued over identical data. Not imported across
 * directories: each approach owns its own copy, and a4 stays untouched
 * evidence.
 *
 * Hand-written rather than generated because the density claim is only tested
 * by real titles: a table of lorem reads as a wireframe, and the column widths
 * a real corpus forces are the whole question this approach is asking.
 */

export type TaskStatus =
	'pending' | 'triaged' | 'building' | 'verifying' | 'done' | 'blocked' | 'wontfix' | 'duplicate';

export type TaskType = 'feature' | 'refactor' | 'chore' | 'spike' | 'bug' | 'adhoc' | 'test';

export type TaskRisk = 'low' | 'medium' | 'high' | 'destructive';

export type Verdict = 'pass' | 'fail' | 'partial';

export interface Task {
	id: string;
	title: string;
	project: string;
	release: string;
	phase: number;
	status: TaskStatus;
	type: TaskType;
	risk: TaskRisk;
	createdOn: string;
	completedOn: string | null;
	stepCount: number;
	criterionCount: number;
	fileChangeCount: number;
	latestAttempt: number;
	latestVerdict: Verdict | null;
	latestSealedOn: string | null;
	/** Task ids this one waits on. Rendered in the expanded row, not as a column. */
	dependsOn: string[];
}

export interface Release {
	slug: string;
	title: string;
	project: string;
	isBucket: boolean;
	tags: string[];
	documentedOn: string | null;
	taskCount: number;
}

export const PROJECTS = [
	'alfons',
	'atlas',
	'ledger',
	'motivka',
	'field-notes',
	'gateway',
	'scratch',
	'agentbench',
	'domovoi',
	'merlin',
	'task-manager'
] as const;

export const RELEASES: Release[] = [
	{
		slug: 'prototype-loop-v1',
		title: 'The prototyping loop — one question at a time, five agents out',
		project: 'alfons',
		isBucket: false,
		tags: ['design-system', 'agents', 'workflow'],
		documentedOn: null,
		taskCount: 9
	},
	{
		slug: 'alfons-mcp',
		title: 'Alfons v1 — one design system, three surfaces',
		project: 'alfons',
		isBucket: false,
		tags: ['design-system', 'mcp'],
		documentedOn: '2026-08-02',
		taskCount: 12
	},
	{
		slug: 'hooks-that-actually-run',
		title: 'Hooks that actually run — one check, four callers',
		project: 'ledger',
		isBucket: false,
		tags: ['governance', 'hooks'],
		documentedOn: '2026-07-29',
		taskCount: 6
	},
	{
		slug: 'schema-comes-home',
		title: 'The schema comes home — a fresh corpus can be built again',
		project: 'ledger',
		isBucket: false,
		tags: ['schema', 'migration'],
		documentedOn: '2026-07-21',
		taskCount: 7
	},
	{
		slug: 'atlas-observability',
		title: 'Atlas observability — every container says what it is doing',
		project: 'atlas',
		isBucket: false,
		tags: ['infra', 'observability'],
		documentedOn: null,
		taskCount: 6
	},
	{
		slug: 'caddy-and-certs',
		title: 'Caddy and certificates — local TLS that never expires quietly',
		project: 'atlas',
		isBucket: false,
		tags: ['infra', 'tls'],
		documentedOn: '2026-07-11',
		taskCount: 4
	},
	{
		slug: 'longread-typography',
		title: 'Longread typography — the article measure and the display voice',
		project: 'motivka',
		isBucket: false,
		tags: ['design', 'editorial'],
		documentedOn: '2026-07-18',
		taskCount: 5
	},
	{
		slug: 'site-measure-v2',
		title: 'Site measure v2 — the grid relaxes where data needs room',
		project: 'motivka',
		isBucket: false,
		tags: ['design', 'layout'],
		documentedOn: null,
		taskCount: 5
	},
	{
		slug: 'field-notes-ingest',
		title: 'Field notes ingest — capture from anywhere, file once',
		project: 'field-notes',
		isBucket: false,
		tags: ['capture', 'sync'],
		documentedOn: null,
		taskCount: 5
	},
	{
		slug: 'gateway-v1',
		title: 'Gateway v1 — one front door for every agent surface',
		project: 'gateway',
		isBucket: false,
		tags: ['infra', 'auth'],
		documentedOn: null,
		taskCount: 5
	},
	{
		slug: 'agentbench-harness',
		title: 'Agentbench harness — evals that fail for the right reason',
		project: 'agentbench',
		isBucket: false,
		tags: ['evals', 'harness'],
		documentedOn: '2026-06-30',
		taskCount: 4
	},
	{
		slug: 'domovoi-daemon',
		title: 'Domovoi — the household daemon that watches the watchers',
		project: 'domovoi',
		isBucket: false,
		tags: ['daemon', 'infra'],
		documentedOn: null,
		taskCount: 4
	},
	{
		slug: 'merlin-recall',
		title: 'Merlin recall — retrieval that admits when it does not know',
		project: 'merlin',
		isBucket: false,
		tags: ['retrieval', 'rag'],
		documentedOn: null,
		taskCount: 4
	},
	{
		slug: 'task-manager-sunset',
		title: 'Task manager sunset — retire the surface the ledger replaced',
		project: 'task-manager',
		isBucket: false,
		tags: ['retirement'],
		documentedOn: '2026-06-14',
		taskCount: 3
	},
	{
		slug: 'scratch',
		title: 'Scratch — unfiled work with nowhere better to sit',
		project: 'scratch',
		isBucket: true,
		tags: ['unfiled'],
		documentedOn: null,
		taskCount: 4
	},
	{
		slug: 'adhoc',
		title: 'Ad hoc — interruptions that earned an id anyway',
		project: 'motivka',
		isBucket: true,
		tags: ['interrupts'],
		documentedOn: null,
		taskCount: 4
	}
];

export const TASKS: Task[] = [
	// prototype-loop-v1 — alfons
	{
		id: 'AL-011',
		title: 'Dev server: serve prototypes from the tree with no registry to update',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-28',
		completedOn: '2026-07-30',
		stepCount: 5,
		criterionCount: 3,
		fileChangeCount: 4,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-30',
		dependsOn: []
	},
	{
		id: 'AL-012',
		title: 'Dev app: production-accurate prototype surface at /dev with pager and work glow',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-29',
		completedOn: '2026-08-01',
		stepCount: 7,
		criterionCount: 4,
		fileChangeCount: 8,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-08-01',
		dependsOn: ['AL-011']
	},
	{
		id: 'AL-013',
		title: 'Round manifest: round.json as the one description five agents read',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-30',
		completedOn: '2026-08-01',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 3,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-08-01',
		dependsOn: ['AL-012']
	},
	{
		id: 'AL-014',
		title: 'Skill: /prototype — the one-question-at-a-time journey and the five-agent fan-out',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 2,
		status: 'verifying',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-31',
		completedOn: null,
		stepCount: 9,
		criterionCount: 6,
		fileChangeCount: 5,
		latestAttempt: 2,
		latestVerdict: 'partial',
		latestSealedOn: '2026-08-03',
		dependsOn: ['AL-013']
	},
	{
		id: 'AL-015',
		title: 'Ownership fences: an agent may write only inside its own approach directory',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 2,
		status: 'building',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-08-01',
		completedOn: null,
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 2,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['AL-014']
	},
	{
		id: 'AL-016',
		title: 'Promotion path: a winning approach moves to a real consumer unchanged',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 3,
		status: 'triaged',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-08-01',
		completedOn: null,
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['AL-015']
	},
	{
		id: 'AL-017',
		title: 'Report the library gap: every local component a round needed, named and costed',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 3,
		status: 'pending',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-08-02',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['AL-016']
	},
	{
		id: 'AL-018',
		title: 'Screenshot every approach at three widths for the review packet',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 3,
		status: 'pending',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-08-02',
		completedOn: null,
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['AL-016']
	},
	{
		id: 'AL-019',
		title: 'Spike: can a round be re-run against a revised brief without losing the old set',
		project: 'alfons',
		release: 'prototype-loop-v1',
		phase: 3,
		status: 'pending',
		type: 'spike',
		risk: 'low',
		createdOn: '2026-08-03',
		completedOn: null,
		stepCount: 2,
		criterionCount: 2,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: []
	},

	// alfons-mcp — alfons
	{
		id: 'AL-001',
		title: 'Token extraction: public and admin surfaces read from one stylesheet pair',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-02',
		completedOn: '2026-07-05',
		stepCount: 8,
		criterionCount: 5,
		fileChangeCount: 11,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-05',
		dependsOn: []
	},
	{
		id: 'AL-002',
		title: 'Component manifest: 82 components described well enough to be found in plain language',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-03',
		completedOn: '2026-07-08',
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 7,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-08',
		dependsOn: ['AL-001']
	},
	{
		id: 'AL-003',
		title:
			'review_markup: literal colours, retired tokens and Svelte 4 idioms caught before commit',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-05',
		completedOn: '2026-07-12',
		stepCount: 12,
		criterionCount: 8,
		fileChangeCount: 14,
		latestAttempt: 3,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-12',
		dependsOn: ['AL-002']
	},
	{
		id: 'AL-004',
		title: 'Layout tiers: shell, region, container — and a rule that reads the same ordering',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-06',
		completedOn: '2026-07-12',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 6,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-12',
		dependsOn: ['AL-002']
	},
	{
		id: 'AL-005',
		title: 'Radius doctrine: every corner squares, and the pill tokens resolve to zero',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 2,
		status: 'done',
		type: 'refactor',
		risk: 'medium',
		createdOn: '2026-07-07',
		completedOn: '2026-07-14',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 23,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-14',
		dependsOn: ['AL-001']
	},
	{
		id: 'AL-006',
		title: 'Elevation ladder: three levels of cast shadow with a rim light that survives dark',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-08',
		completedOn: '2026-07-15',
		stepCount: 6,
		criterionCount: 5,
		fileChangeCount: 9,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-15',
		dependsOn: ['AL-001']
	},
	{
		id: 'AL-007',
		title: 'Deprecation answers name their replacement and the decision that retired them',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 3,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-10',
		completedOn: '2026-07-19',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 5,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-19',
		dependsOn: ['AL-003']
	},
	{
		id: 'AL-008',
		title: 'Findings are advisory: the reviewer never fails a build',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 3,
		status: 'done',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-07-11',
		completedOn: '2026-07-19',
		stepCount: 2,
		criterionCount: 2,
		fileChangeCount: 2,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-19',
		dependsOn: ['AL-003']
	},
	{
		id: 'AL-009',
		title: 'Tailwind shadowing: warn when a utility silently overrides a token',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 3,
		status: 'done',
		type: 'bug',
		risk: 'medium',
		createdOn: '2026-07-14',
		completedOn: '2026-07-22',
		stepCount: 7,
		criterionCount: 4,
		fileChangeCount: 4,
		latestAttempt: 3,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-22',
		dependsOn: ['AL-003']
	},
	{
		id: 'AL-010',
		title: 'Rules baseline: freeze current findings so a regression is visible',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 3,
		status: 'done',
		type: 'test',
		risk: 'low',
		createdOn: '2026-07-16',
		completedOn: '2026-07-24',
		stepCount: 3,
		criterionCount: 3,
		fileChangeCount: 3,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-24',
		dependsOn: ['AL-009']
	},
	{
		id: 'AL-020',
		title: 'Storybook catalogue published so a human can browse what an agent searches',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 4,
		status: 'blocked',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-07-25',
		completedOn: null,
		stepCount: 4,
		criterionCount: 2,
		fileChangeCount: 1,
		latestAttempt: 1,
		latestVerdict: 'fail',
		latestSealedOn: '2026-07-27',
		dependsOn: ['ATL-118']
	},
	{
		id: 'AL-021',
		title: 'Scaffold a component from the manifest rather than from a blank file',
		project: 'alfons',
		release: 'alfons-mcp',
		phase: 4,
		status: 'triaged',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-26',
		completedOn: null,
		stepCount: 5,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['AL-002']
	},

	// hooks-that-actually-run — ledger
	{
		id: 'LDG-038',
		title: 'One release-document check, four callers — hook, CLI, MCP and CI',
		project: 'ledger',
		release: 'hooks-that-actually-run',
		phase: 1,
		status: 'done',
		type: 'refactor',
		risk: 'medium',
		createdOn: '2026-07-24',
		completedOn: '2026-07-28',
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 9,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-28',
		dependsOn: []
	},
	{
		id: 'LDG-039',
		title: 'Probe psql-18: bare psql resolves only in an interactive shell',
		project: 'ledger',
		release: 'hooks-that-actually-run',
		phase: 1,
		status: 'done',
		type: 'bug',
		risk: 'low',
		createdOn: '2026-07-24',
		completedOn: '2026-07-26',
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 4,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-26',
		dependsOn: []
	},
	{
		id: 'LDG-040',
		title: 'Say when the server has drifted from the schema it was built against',
		project: 'ledger',
		release: 'hooks-that-actually-run',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-25',
		completedOn: '2026-07-29',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 6,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-29',
		dependsOn: ['LDG-039']
	},
	{
		id: 'LDG-041',
		title: 'Branch is the release: refuse a write when the repository stands elsewhere',
		project: 'ledger',
		release: 'hooks-that-actually-run',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-25',
		completedOn: '2026-07-29',
		stepCount: 8,
		criterionCount: 6,
		fileChangeCount: 7,
		latestAttempt: 3,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-29',
		dependsOn: ['LDG-038']
	},
	{
		id: 'LDG-042',
		title: 'Fail open on a detached or unborn HEAD — unknowable is not the same as wrong',
		project: 'ledger',
		release: 'hooks-that-actually-run',
		phase: 2,
		status: 'done',
		type: 'bug',
		risk: 'medium',
		createdOn: '2026-07-26',
		completedOn: '2026-07-29',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 3,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-29',
		dependsOn: ['LDG-041']
	},
	{
		id: 'LDG-043',
		title: 'Scope rules to the repository so a shared hook stops leaking across trees',
		project: 'ledger',
		release: 'hooks-that-actually-run',
		phase: 3,
		status: 'verifying',
		type: 'refactor',
		risk: 'medium',
		createdOn: '2026-07-28',
		completedOn: null,
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 5,
		latestAttempt: 1,
		latestVerdict: 'partial',
		latestSealedOn: '2026-08-02',
		dependsOn: ['LDG-042']
	},

	// schema-comes-home — ledger
	{
		id: 'LDG-030',
		title: 'Move the DDL out of the repository being dismantled and into the server that serves it',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 1,
		status: 'done',
		type: 'chore',
		risk: 'high',
		createdOn: '2026-07-14',
		completedOn: '2026-07-16',
		stepCount: 5,
		criterionCount: 3,
		fileChangeCount: 18,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-16',
		dependsOn: []
	},
	{
		id: 'LDG-031',
		title: 'base.sql is generated from the live corpus, never hand-written',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-14',
		completedOn: '2026-07-17',
		stepCount: 6,
		criterionCount: 5,
		fileChangeCount: 4,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-17',
		dependsOn: ['LDG-030']
	},
	{
		id: 'LDG-032',
		title: 'Emit CREATE EXTENSION ourselves — pg_dump says nothing about them',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 2,
		status: 'done',
		type: 'bug',
		risk: 'medium',
		createdOn: '2026-07-15',
		completedOn: '2026-07-18',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 2,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-18',
		dependsOn: ['LDG-031']
	},
	{
		id: 'LDG-033',
		title: 'Compare trigger definitions with search_path emptied on both connections',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 2,
		status: 'done',
		type: 'test',
		risk: 'low',
		createdOn: '2026-07-16',
		completedOn: '2026-07-19',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 3,
		latestAttempt: 3,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-19',
		dependsOn: ['LDG-031']
	},
	{
		id: 'LDG-034',
		title: 'base.manifest records what the base file already contains, Flyway-style',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-17',
		completedOn: '2026-07-20',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 3,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-20',
		dependsOn: ['LDG-031']
	},
	{
		id: 'LDG-035',
		title: 'Drop xml_text and delete the definition, so ten migrations stop recreating it',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 3,
		status: 'done',
		type: 'refactor',
		risk: 'destructive',
		createdOn: '2026-07-18',
		completedOn: '2026-07-21',
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 12,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-21',
		dependsOn: ['LDG-033']
	},
	{
		id: 'LDG-036',
		title: 'btrim strips spaces, not newlines — spell the character set out',
		project: 'ledger',
		release: 'schema-comes-home',
		phase: 3,
		status: 'done',
		type: 'bug',
		risk: 'high',
		createdOn: '2026-07-19',
		completedOn: '2026-07-21',
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 2,
		latestAttempt: 4,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-21',
		dependsOn: ['LDG-035']
	},

	// atlas-observability — atlas
	{
		id: 'ATL-115',
		title: 'Every container emits a structured start line naming its build',
		project: 'atlas',
		release: 'atlas-observability',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-20',
		completedOn: '2026-07-24',
		stepCount: 5,
		criterionCount: 3,
		fileChangeCount: 9,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-24',
		dependsOn: []
	},
	{
		id: 'ATL-116',
		title: 'Log shipping without a sidecar per service',
		project: 'atlas',
		release: 'atlas-observability',
		phase: 1,
		status: 'building',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-22',
		completedOn: null,
		stepCount: 7,
		criterionCount: 5,
		fileChangeCount: 4,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['ATL-115']
	},
	{
		id: 'ATL-117',
		title: 'Health endpoints that fail loudly rather than answering 200 while broken',
		project: 'atlas',
		release: 'atlas-observability',
		phase: 2,
		status: 'triaged',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-24',
		completedOn: null,
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['ATL-116']
	},
	{
		id: 'ATL-118',
		title: 'Static site hosting for Storybook behind the same reverse proxy',
		project: 'atlas',
		release: 'atlas-observability',
		phase: 2,
		status: 'blocked',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-25',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 2,
		latestAttempt: 2,
		latestVerdict: 'fail',
		latestSealedOn: '2026-07-30',
		dependsOn: ['ATL-121']
	},
	{
		id: 'ATL-119',
		title: 'Retention policy: keep 14 days hot and nothing after 90',
		project: 'atlas',
		release: 'atlas-observability',
		phase: 3,
		status: 'pending',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-07-28',
		completedOn: null,
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['ATL-116']
	},
	{
		id: 'ATL-120',
		title: 'Spike: is a metrics store worth running for eleven projects',
		project: 'atlas',
		release: 'atlas-observability',
		phase: 3,
		status: 'wontfix',
		type: 'spike',
		risk: 'low',
		createdOn: '2026-07-29',
		completedOn: '2026-08-01',
		stepCount: 2,
		criterionCount: 1,
		fileChangeCount: 0,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-08-01',
		dependsOn: []
	},

	// caddy-and-certs — atlas
	{
		id: 'ATL-110',
		title: 'Local TLS with a root the whole machine trusts',
		project: 'atlas',
		release: 'caddy-and-certs',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-04',
		completedOn: '2026-07-08',
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 5,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-08',
		dependsOn: []
	},
	{
		id: 'ATL-111',
		title: 'Reverse proxy every dev surface under one hostname',
		project: 'atlas',
		release: 'caddy-and-certs',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-05',
		completedOn: '2026-07-09',
		stepCount: 5,
		criterionCount: 3,
		fileChangeCount: 4,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-09',
		dependsOn: ['ATL-110']
	},
	{
		id: 'ATL-112',
		title: 'Warn before a certificate expires rather than after the browser does',
		project: 'atlas',
		release: 'caddy-and-certs',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-07',
		completedOn: '2026-07-11',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 3,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-11',
		dependsOn: ['ATL-110']
	},
	{
		id: 'ATL-121',
		title: 'Path-preserving proxy for bases other than root',
		project: 'atlas',
		release: 'caddy-and-certs',
		phase: 2,
		status: 'building',
		type: 'bug',
		risk: 'medium',
		createdOn: '2026-07-27',
		completedOn: null,
		stepCount: 5,
		criterionCount: 3,
		fileChangeCount: 2,
		latestAttempt: 2,
		latestVerdict: 'fail',
		latestSealedOn: '2026-08-01',
		dependsOn: ['ATL-111']
	},

	// longread-typography — motivka
	{
		id: 'MTV-070',
		title: 'The article measure: one column, sixty-six characters, no exceptions',
		project: 'motivka',
		release: 'longread-typography',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-09',
		completedOn: '2026-07-14',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 6,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-14',
		dependsOn: []
	},
	{
		id: 'MTV-071',
		title: 'Display serif for headings, mono for microtype, body for everything else',
		project: 'motivka',
		release: 'longread-typography',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-09',
		completedOn: '2026-07-15',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 8,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-15',
		dependsOn: ['MTV-070']
	},
	{
		id: 'MTV-072',
		title: 'Stat band: two or three figures a piece stakes its credibility on',
		project: 'motivka',
		release: 'longread-typography',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-11',
		completedOn: '2026-07-17',
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 4,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-17',
		dependsOn: ['MTV-071']
	},
	{
		id: 'MTV-073',
		title: 'Drop cap that survives a two-line heading above it',
		project: 'motivka',
		release: 'longread-typography',
		phase: 2,
		status: 'done',
		type: 'bug',
		risk: 'low',
		createdOn: '2026-07-13',
		completedOn: '2026-07-18',
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 2,
		latestAttempt: 3,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-18',
		dependsOn: ['MTV-071']
	},
	{
		id: 'MTV-074',
		title: 'Figure captions read as evidence, not as decoration',
		project: 'motivka',
		release: 'longread-typography',
		phase: 3,
		status: 'duplicate',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-07-15',
		completedOn: '2026-07-16',
		stepCount: 1,
		criterionCount: 1,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MTV-072']
	},

	// site-measure-v2 — motivka
	{
		id: 'MTV-080',
		title: 'Relax the blog measure where a table or a grid needs the width',
		project: 'motivka',
		release: 'site-measure-v2',
		phase: 1,
		status: 'building',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-30',
		completedOn: null,
		stepCount: 6,
		criterionCount: 5,
		fileChangeCount: 3,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: []
	},
	{
		id: 'MTV-081',
		title: 'Header and footer stay put on every page, however wide the content runs',
		project: 'motivka',
		release: 'site-measure-v2',
		phase: 1,
		status: 'triaged',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-07-30',
		completedOn: null,
		stepCount: 3,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MTV-080']
	},
	{
		id: 'MTV-082',
		title: 'Ledger dashboard: rebuild the page Simon actually opens every morning',
		project: 'motivka',
		release: 'site-measure-v2',
		phase: 2,
		status: 'building',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-08-01',
		completedOn: null,
		stepCount: 9,
		criterionCount: 7,
		fileChangeCount: 6,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MTV-080', 'AL-014']
	},
	{
		id: 'MTV-083',
		title: 'SSE feed corrects task status underneath the view without a reload',
		project: 'motivka',
		release: 'site-measure-v2',
		phase: 2,
		status: 'triaged',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-08-01',
		completedOn: null,
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MTV-082']
	},
	{
		id: 'MTV-084',
		title: 'Print stylesheet so a release can be read on paper in a review',
		project: 'motivka',
		release: 'site-measure-v2',
		phase: 3,
		status: 'pending',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-08-02',
		completedOn: null,
		stepCount: 2,
		criterionCount: 2,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MTV-082']
	},

	// field-notes-ingest — field-notes
	{
		id: 'FN-021',
		title: 'Capture from the phone share sheet into the inbox with no app open',
		project: 'field-notes',
		release: 'field-notes-ingest',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-17',
		completedOn: '2026-07-23',
		stepCount: 7,
		criterionCount: 5,
		fileChangeCount: 8,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-23',
		dependsOn: []
	},
	{
		id: 'FN-022',
		title: 'Deduplicate a note captured twice from two devices',
		project: 'field-notes',
		release: 'field-notes-ingest',
		phase: 2,
		status: 'verifying',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-21',
		completedOn: null,
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 4,
		latestAttempt: 2,
		latestVerdict: 'partial',
		latestSealedOn: '2026-08-02',
		dependsOn: ['FN-021']
	},
	{
		id: 'FN-023',
		title: 'File a note against a project without asking which one twice',
		project: 'field-notes',
		release: 'field-notes-ingest',
		phase: 2,
		status: 'building',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-24',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 2,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['FN-021']
	},
	{
		id: 'FN-024',
		title: 'Offline queue that survives a force quit',
		project: 'field-notes',
		release: 'field-notes-ingest',
		phase: 3,
		status: 'pending',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-28',
		completedOn: null,
		stepCount: 6,
		criterionCount: 4,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['FN-023']
	},
	{
		id: 'FN-025',
		title: 'Attachment sizes capped before upload, not after',
		project: 'field-notes',
		release: 'field-notes-ingest',
		phase: 3,
		status: 'pending',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-07-31',
		completedOn: null,
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['FN-024']
	},

	// gateway-v1 — gateway
	{
		id: 'GW-007',
		title: 'One front door: every agent surface authenticates the same way',
		project: 'gateway',
		release: 'gateway-v1',
		phase: 1,
		status: 'building',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-26',
		completedOn: null,
		stepCount: 9,
		criterionCount: 6,
		fileChangeCount: 7,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: []
	},
	{
		id: 'GW-008',
		title: 'Token rotation without an outage window',
		project: 'gateway',
		release: 'gateway-v1',
		phase: 2,
		status: 'triaged',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-27',
		completedOn: null,
		stepCount: 6,
		criterionCount: 5,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['GW-007']
	},
	{
		id: 'GW-009',
		title: 'Rate limits stated in the response, not discovered by being cut off',
		project: 'gateway',
		release: 'gateway-v1',
		phase: 2,
		status: 'pending',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-29',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['GW-007']
	},
	{
		id: 'GW-010',
		title: 'Audit log every credential use, append-only',
		project: 'gateway',
		release: 'gateway-v1',
		phase: 3,
		status: 'pending',
		type: 'feature',
		risk: 'destructive',
		createdOn: '2026-07-31',
		completedOn: null,
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['GW-008']
	},
	{
		id: 'GW-011',
		title: 'Spike: does the gateway belong in front of the MCP servers at all',
		project: 'gateway',
		release: 'gateway-v1',
		phase: 1,
		status: 'done',
		type: 'spike',
		risk: 'low',
		createdOn: '2026-07-23',
		completedOn: '2026-07-25',
		stepCount: 2,
		criterionCount: 2,
		fileChangeCount: 1,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-25',
		dependsOn: []
	},

	// agentbench-harness — agentbench
	{
		id: 'AB-014',
		title: 'An eval fails for the reason it names, or it is not an eval',
		project: 'agentbench',
		release: 'agentbench-harness',
		phase: 1,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-06-20',
		completedOn: '2026-06-26',
		stepCount: 6,
		criterionCount: 5,
		fileChangeCount: 9,
		latestAttempt: 3,
		latestVerdict: 'pass',
		latestSealedOn: '2026-06-26',
		dependsOn: []
	},
	{
		id: 'AB-015',
		title: 'Harvest eval tasks from what actually went wrong in a session',
		project: 'agentbench',
		release: 'agentbench-harness',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-06-22',
		completedOn: '2026-06-29',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 5,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-06-29',
		dependsOn: ['AB-014']
	},
	{
		id: 'AB-016',
		title: 'Variance analysis so one lucky run is not read as a result',
		project: 'agentbench',
		release: 'agentbench-harness',
		phase: 2,
		status: 'done',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-06-24',
		completedOn: '2026-06-30',
		stepCount: 7,
		criterionCount: 5,
		fileChangeCount: 6,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-06-30',
		dependsOn: ['AB-014']
	},
	{
		id: 'AB-017',
		title: 'Run the suite nightly and only speak up when a number moves',
		project: 'agentbench',
		release: 'agentbench-harness',
		phase: 3,
		status: 'blocked',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-06-28',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 1,
		latestAttempt: 1,
		latestVerdict: 'fail',
		latestSealedOn: '2026-07-02',
		dependsOn: ['ATL-116']
	},

	// domovoi-daemon — domovoi
	{
		id: 'DOM-005',
		title: 'The daemon that watches the watchers and restarts what died quietly',
		project: 'domovoi',
		release: 'domovoi-daemon',
		phase: 1,
		status: 'building',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-19',
		completedOn: null,
		stepCount: 8,
		criterionCount: 6,
		fileChangeCount: 6,
		latestAttempt: 2,
		latestVerdict: 'partial',
		latestSealedOn: '2026-07-31',
		dependsOn: []
	},
	{
		id: 'DOM-006',
		title: 'Back off rather than thrash when a service refuses to come up',
		project: 'domovoi',
		release: 'domovoi-daemon',
		phase: 2,
		status: 'triaged',
		type: 'bug',
		risk: 'medium',
		createdOn: '2026-07-22',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['DOM-005']
	},
	{
		id: 'DOM-007',
		title: 'One notification per incident, not one per retry',
		project: 'domovoi',
		release: 'domovoi-daemon',
		phase: 2,
		status: 'pending',
		type: 'feature',
		risk: 'low',
		createdOn: '2026-07-26',
		completedOn: null,
		stepCount: 3,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['DOM-006']
	},
	{
		id: 'DOM-008',
		title: 'Refuse to supervise anything without a health endpoint',
		project: 'domovoi',
		release: 'domovoi-daemon',
		phase: 3,
		status: 'pending',
		type: 'chore',
		risk: 'medium',
		createdOn: '2026-07-30',
		completedOn: null,
		stepCount: 2,
		criterionCount: 2,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['ATL-117']
	},

	// merlin-recall — merlin
	{
		id: 'MRL-032',
		title: 'Retrieval that admits when it does not know rather than inventing a citation',
		project: 'merlin',
		release: 'merlin-recall',
		phase: 1,
		status: 'verifying',
		type: 'feature',
		risk: 'high',
		createdOn: '2026-07-15',
		completedOn: null,
		stepCount: 9,
		criterionCount: 7,
		fileChangeCount: 11,
		latestAttempt: 3,
		latestVerdict: 'partial',
		latestSealedOn: '2026-08-01',
		dependsOn: []
	},
	{
		id: 'MRL-033',
		title: 'Chunking that respects a heading boundary',
		project: 'merlin',
		release: 'merlin-recall',
		phase: 1,
		status: 'done',
		type: 'refactor',
		risk: 'medium',
		createdOn: '2026-07-13',
		completedOn: '2026-07-20',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 4,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-20',
		dependsOn: []
	},
	{
		id: 'MRL-034',
		title: 'Rerank locally so a bad first-stage recall is recoverable',
		project: 'merlin',
		release: 'merlin-recall',
		phase: 2,
		status: 'triaged',
		type: 'feature',
		risk: 'medium',
		createdOn: '2026-07-25',
		completedOn: null,
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MRL-032']
	},
	{
		id: 'MRL-035',
		title: 'Evaluate recall against a set Simon wrote by hand',
		project: 'merlin',
		release: 'merlin-recall',
		phase: 3,
		status: 'pending',
		type: 'test',
		risk: 'low',
		createdOn: '2026-07-29',
		completedOn: null,
		stepCount: 4,
		criterionCount: 3,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MRL-034', 'AB-015']
	},

	// task-manager-sunset — task-manager
	{
		id: 'TM-041',
		title: 'Export every open item into the ledger before the lights go out',
		project: 'task-manager',
		release: 'task-manager-sunset',
		phase: 1,
		status: 'done',
		type: 'chore',
		risk: 'destructive',
		createdOn: '2026-06-02',
		completedOn: '2026-06-09',
		stepCount: 6,
		criterionCount: 5,
		fileChangeCount: 7,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-06-09',
		dependsOn: []
	},
	{
		id: 'TM-042',
		title: 'Redirect the old URLs rather than letting them 404 for a year',
		project: 'task-manager',
		release: 'task-manager-sunset',
		phase: 2,
		status: 'done',
		type: 'chore',
		risk: 'low',
		createdOn: '2026-06-04',
		completedOn: '2026-06-12',
		stepCount: 3,
		criterionCount: 2,
		fileChangeCount: 3,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-06-12',
		dependsOn: ['TM-041']
	},
	{
		id: 'TM-043',
		title: 'Archive the database and prove it restores before deleting anything',
		project: 'task-manager',
		release: 'task-manager-sunset',
		phase: 3,
		status: 'done',
		type: 'chore',
		risk: 'destructive',
		createdOn: '2026-06-06',
		completedOn: '2026-06-14',
		stepCount: 5,
		criterionCount: 4,
		fileChangeCount: 2,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-06-14',
		dependsOn: ['TM-042']
	},

	// scratch — bucket
	{
		id: 'SCR-058',
		title: 'Work out why the fan noise correlates with the nightly eval run',
		project: 'scratch',
		release: 'scratch',
		phase: 1,
		status: 'pending',
		type: 'spike',
		risk: 'low',
		createdOn: '2026-07-27',
		completedOn: null,
		stepCount: 1,
		criterionCount: 1,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: []
	},
	{
		id: 'SCR-059',
		title: 'Try a tabular-numeral mono for every figure column across the site',
		project: 'scratch',
		release: 'scratch',
		phase: 1,
		status: 'triaged',
		type: 'spike',
		risk: 'low',
		createdOn: '2026-07-30',
		completedOn: null,
		stepCount: 2,
		criterionCount: 1,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: []
	},
	{
		id: 'SCR-060',
		title: 'Colour-blind pass over every status encoding on every surface',
		project: 'scratch',
		release: 'scratch',
		phase: 1,
		status: 'building',
		type: 'chore',
		risk: 'medium',
		createdOn: '2026-08-01',
		completedOn: null,
		stepCount: 3,
		criterionCount: 3,
		fileChangeCount: 1,
		latestAttempt: 1,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: []
	},
	{
		id: 'SCR-061',
		title: 'Old prototype round left half-built after the brief changed',
		project: 'scratch',
		release: 'scratch',
		phase: 1,
		status: 'wontfix',
		type: 'adhoc',
		risk: 'low',
		createdOn: '2026-07-12',
		completedOn: '2026-07-26',
		stepCount: 1,
		criterionCount: 1,
		fileChangeCount: 0,
		latestAttempt: 1,
		latestVerdict: 'fail',
		latestSealedOn: '2026-07-26',
		dependsOn: []
	},

	// adhoc — bucket
	{
		id: 'MTV-090',
		title: 'Fix the footer contact link pointing at the retired address',
		project: 'motivka',
		release: 'adhoc',
		phase: 1,
		status: 'done',
		type: 'adhoc',
		risk: 'low',
		createdOn: '2026-07-31',
		completedOn: '2026-07-31',
		stepCount: 1,
		criterionCount: 1,
		fileChangeCount: 1,
		latestAttempt: 1,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-31',
		dependsOn: []
	},
	{
		id: 'MTV-091',
		title: 'Interruption: the header wordmark shifted a pixel on Safari after a font update',
		project: 'motivka',
		release: 'adhoc',
		phase: 1,
		status: 'done',
		type: 'bug',
		risk: 'low',
		createdOn: '2026-07-28',
		completedOn: '2026-07-29',
		stepCount: 2,
		criterionCount: 1,
		fileChangeCount: 1,
		latestAttempt: 2,
		latestVerdict: 'pass',
		latestSealedOn: '2026-07-29',
		dependsOn: []
	},
	{
		id: 'MTV-092',
		title: 'Duplicate of the measure work already tracked in site-measure-v2',
		project: 'motivka',
		release: 'adhoc',
		phase: 1,
		status: 'duplicate',
		type: 'adhoc',
		risk: 'low',
		createdOn: '2026-07-30',
		completedOn: '2026-07-30',
		stepCount: 1,
		criterionCount: 1,
		fileChangeCount: 0,
		latestAttempt: 0,
		latestVerdict: null,
		latestSealedOn: null,
		dependsOn: ['MTV-080']
	},
	{
		id: 'MTV-093',
		title: 'Reduce the newsletter row to one line on mobile',
		project: 'motivka',
		release: 'adhoc',
		phase: 1,
		status: 'verifying',
		type: 'adhoc',
		risk: 'low',
		createdOn: '2026-08-02',
		completedOn: null,
		stepCount: 2,
		criterionCount: 2,
		fileChangeCount: 2,
		latestAttempt: 1,
		latestVerdict: 'partial',
		latestSealedOn: '2026-08-03',
		dependsOn: []
	}
];

export const RELEASE_BY_SLUG = new Map(RELEASES.map((release) => [release.slug, release]));

/** Statuses that mean the work is not finished and has not been abandoned. */
export const OPEN_STATUSES: TaskStatus[] = ['pending', 'triaged', 'building', 'verifying'];

/** Statuses that mean an agent or a person is actively on it right now. */
export const IN_FLIGHT_STATUSES: TaskStatus[] = ['building', 'verifying'];
